### ISSUE TITLE
Model (ddi-cdi_ea15.eapx) cann't be opened using Enterprise Architect Viewer Version 17.0

### ISSUE THREAD

**Issue by kwenzig** [ddi-cdi/ddi-cdi#1]
It is difficult to get an overview over the model, the field-level documentation shows only single classes, while context and overview get lost.

The Model Specification in ddi-cdi_ea15.eapx is an Enterprise Architect File. For Enterprise Architect a _free_ viewer is available, but the [Enterprise Architect Viewer Version 17.0](https://sparxsystems.com/products/ea/downloads.html) reports, that it cannot open a legacy format.
![image](https://github.com/user-attachments/assets/57461fd7-abbe-4046-adbe-79867e578883)
Would it be possible to provide the model in a more recent format?

**Comment by achimwackerow** [comment]
The model work is done with Enterprise Architect version 15. The file extension eapx is related to a Microsoft Jet 4.0 database.
I created a Firebird repository which might be more portable. For the different Enterprise Architect file see: https://sparxsystems.com/enterprise_architect_user_guide/17.0/the_model_repository/createamodeloverview.html .

Please try the ddi-cdi_ea15.feap file in the attached [ddi-cdi_ea15.zip](https://github.com/user-attachments/files/17736628/ddi-cdi_ea15.zip) file and report back. Do you use the 32bit or 64bit version of the viewer?

Please note that I can't try the viewer because EA doesn't really allow parallel installations.

**Comment by kwenzig** [comment]
The ddi-cdi_ea15.feap you provided can be opened with the (free) 64bit-read-only version of Enterprise Architect 17.0.1703. In the Diagrams folder I found more than 30 diagrams (Catalog Details, Classification as a Collection etc.). There are some options to navigate between those pre-fabricated diagrams and find diagrams which contain a specific element. I expected that there is also some (generic) graphical overview over the model (like a big picture), which allows to navigate and dig deeper at a given point, but this feature does not seem to be available in the software.
